### ISSUE TITLE
Request: option to manually set exe path

### ISSUE THREAD

**Issue by jacobisleib** [giswqs/whiteboxR#37]
Greetings, I use whiteboxtools with limited admin privileges (government work pc) and am unable to run the executable from my R directory.  However, I can have WhiteBoxTools installed to my work computer and run via console from the C:/ProgramFiles.. directory.   I'd love to be able to script whitebox in R but would need to manually set the exe path.  I've tried to see if this is possible in the current version but believe it is not.  Thanks for your consideration!

**Comment by bkielstr** [comment]
Hi @jacobisleib 

I think that this will be addressed in when I deal with #4. I'll be working on whiteboxR CRAN-compliant within the next month or so.

Do you have a user R library (e.g., C:/Documents/R/win-library)? Or is that not allowed on your machine? Shifting your library to another local location might help. I am also on a government pc with limited admin privileges.

**Comment by jacobisleib** [comment]
Hi,
That's great!   I appreciate your work on this software.

Yes, I have a local R library but I think all non-admin installed exe files get restricted as far as I can tell.

**Comment by giswqs** [comment]
@jacobisleib Maybe you can try Google Colab as a temporary solution before this feature is implemented. 

https://colab.research.google.com/drive/1V7ID9AWz_kI8S88Z6nZxzPJz3G3lM6Or?usp=sharing

**Comment by brownag** [comment]
Hi @giswqs and @bkielstr 

I forked the repo and played around a bit after stumbling upon @jacobisleib's issue. I work for same agency as Jacob. We only have execute permissions in certain directories, and non-privileged users can't put new executable into these folders. We _can_ have our IT folks install WBT into Program Files (for instance), and once it is in that folder we just need a way to point package to that path. I would be happy to open a PR to close this issue.

---

Here is a shortlist of what I implemented so far on https://github.com/brownag/whiteboxR/tree/customexe just to see how it would work. 

 ### Add options for custom EXE path 

 * Changes behavior of `wbt_init()` 
    * now only checks EXE path
 * Adds `wbt_install()` to handle downloading and installing WhiteboxTools
    * this updates the onload instructions to say use `wbt_install()` when EXE not found
 * Abstraction of EXE path finding in `check_whitebox_binary()` (pretty) / `wbt_exe_path()` (internal use)
    * added a couple methods to help with finding paths, these use either a system environment variable `R_WHITEBOX_EXE_PATH` or a package option `whitebox.exe_path` or an argument
    * I made a couple decisions here regarding how/when messages are printed and some heuristics for finding binaries that may not be ready for prime-time. Happy to discuss.

### Changes to tests
 * all of the automatically-generated testing code now includes the line `skip_if_not(check_whitebox_binary())` which allows tests to be skipped if a binary isn't present. 

---

If you want @bkielstr I would be happy to collaborate/chat with you and @giswqs to get {whitebox} back on CRAN. But I don't want to step on any toes; sorry for mysteriously tagging this issue and providing no explanation last week. I have a couple CRAN packages I maintain or help maintain... so I know a little bit on that front. 

If my PR for this issue work, and another solution is not yet available, I would love to contribute. Otherwise, just happy to join in the conversation. I have a few other ideas for improved integration with R that I could suggest in future.

**Comment by giswqs** [comment]
@brownag Thank you very much for this. Your implementation looks great. Please feel free to submit a pull request. I have also added you as a collaborator for this repo. My R knowledge is quite limited as I have not actively used it during the past years. Your contribution will be greatly appreciated. If you can make whiteboxR acceptable by CRAN, that would be awesome! Any potential solution is welcome. No need to wait. @bkielstr and others can improve your solution if needed.

**Comment by bkielstr** [comment]
@brownag - I certainly don't think you're stepping on any toes.  I was mostly trying to keep the conversation about CRAN and was willing to tackle it - it looks like you've moved it all the way forward! And other than forking the repository, I haven't had the chance to get moving on this. By chance, I saw the branch you were working on a few days ago and thought it was the perfect solution for CRAN. 

So @brownag and @giswqs - the next steps are accepting the PR and then @brownag are you going to to try for submitting to CRAN? I'm happy to contribute to any testing (on my work computer and home mac setup) or help submitting. Just send a task my way.

**Comment by brownag** [comment]
Once PR is merged I would be happy to try and submit to see what they have to say and go from there
I have tested it on my work computer (windows) and my home computer (ubuntu), but please test and look for any pain points.

**Comment by giswqs** [comment]
@brownag Great work! Thanks a lot.
