### ISSUE TITLE
Add machine learning tools and improve automation script

### ISSUE THREAD

**Issue by giswqs** [giswqs/whiteboxR#58]
Currently, the machine learning tools are missing. The automation script needs to be improved. 

https://www.whiteboxgeo.com/manual/wbt_book/available_tools/machine_learning.html

toolboxes 
https://github.com/giswqs/whiteboxR/blob/master/PY2R/automation.py#L216

get_wbt_dict:
https://github.com/giswqs/whiteboxgui/blob/master/whiteboxgui/whiteboxgui.py#L364

get_ext_dict:
https://github.com/giswqs/whiteboxgui/blob/master/whiteboxgui/whiteboxgui.py#L280

**Comment by brownag** [comment]
The functions for ML tools linked in the [WBT manual](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/machine_learning.html) were created by automation script and are now exported from the R package. I think they should "work" for folks who have the extension to activate (but have not tested), and they show up in the documentation e.g. https://giswqs.github.io/whiteboxR/reference/wbt_dbscan.html

ML tools are currently being defined in _R/lidar_analysis.R_, which is not right ... but makes sense given lack of handling of that toolbox and their order in source .py file. Should be easy fix.

Metadata (in R datasets `wbttools` and `wbttoolparams`) for the ML methods is currently missing because when I generate those data the names and parameters come from the output of `wbt_list_tools()` / `wbt_tool_parameters()`  I think they don't show up because I don't have the extensions? I was taking a look at how you are handling it https://github.com/giswqs/whiteboxgui/ v.s. current approach for the R package and I think this could be fixed pretty easily to just work off the whitebox_tools.json... is this what you have in mind?

**Comment by giswqs** [comment]
I have added the machine learning tools to `machine_learning.R`. It was an easy fix. See PR #59. 

You can use Python `wbt.install_wbt_extension("gte")` to install the extensions. See 
https://github.com/giswqs/whitebox-python/blob/master/whitebox/whitebox_tools.py#L584

Each extension tool has an associated json file with all the parameters listed in it. Therefore, you don't need a license to retrieve the tool parameters, but you do need a license if you need to run the tool. 

Ideally, we should be able to use [whitebox_tools.json](https://raw.githubusercontent.com/giswqs/whiteboxgui/master/whiteboxgui/data/whitebox_tools.json) to retrieve all the tool parameters (open-core+extensions). It will take some time to update [automation.py](https://github.com/giswqs/whiteboxR/blob/master/PY2R/automation.py). Since the current method still works, we can just keep it as it is. 

You can build upon my PR to add the R datasets. I have not used R for a while. Not sure how to do this.
