### ISSUE TITLE
working with R internal files

### ISSUE THREAD

**Issue by wiesehahn** [giswqs/whiteboxR#69]
Hi, 
is there any way to process files internally in R without saving them to disk?

something like e.g. 
```
## 1. FeaturePreservingSmoothing
dem_smoothed <- wbt_feature_preserving_smoothing(
  dem = dem,
  filter = 9
  )
```

**Comment by brownag** [comment]
The short answer is no because the R package is a wrapper around the Rust library and command line tool: https://github.com/jblindsay/whitebox-tools. All of the arguments for inputs and outputs of the tool in are specified as file paths.

I have been experimenting with an alternative interface for calling tools that allows automatic creation of R spatial objects from the inputs and outputs via a new wrapper method called `wbt()`. See https://github.com/giswqs/whiteboxR/pull/48/ / `remotes::install_github("brownag/whiteboxR@wbtTool")`. If you would like to try it out I would appreciate the feedback. However, this still will ultimately rely on writing outputs to (possibly temporary) files. I did have a plan to possibly generate file names systematically based on the tool, file inputs, parameters etc. which would further simplify making the calls (i.e. would not need to specify `output`)

``` r
library(whitebox)
library(terra)
input <- rast(sample_dem_data())
crs(input) <- "EPSG:32618"
res <- wbt("FeaturePreservingSmoothing", dem = input, output = "foo.tif", filter = 9) |> 
  get_result()
res
#> [[1]]
#> class       : SpatRaster 
#> dimensions  : 188, 237, 1  (nrow, ncol, nlyr)
#> resolution  : 89.9835, 90.02154  (x, y)
#> extent      : 664692.1, 686018.1, 4878904, 4895828  (xmin, xmax, ymin, ymax)
#> coord. ref. : WGS 84 / UTM zone 18N (EPSG:32618) 
#> source      : foo.tif 
#> name        : foo
sources(res[[1]])
#> [1] "/tmp/Rtmp73A86t/reprex559d542afa1c1/foo.tif"
```

**Comment by wiesehahn** [comment]
After long time I wanted to test this, but I am struggling with the installation. 

After `remotes::install_github("brownag/whiteboxR@wbtTool")` WhiteboxTools can not be found by `library(whitebox)` and maunally pointing towards the recently created folder by `wbt_init(exe_path="C:/Program Files/R/R-4.1.3/library/whitebox")` results in `Error in system(exeargs, intern = TRUE, ignore.stderr = ignore.stderr, : '"C:/Program Files/R/R-4.1.3/library/whitebox"' not found` later when running the `wbt()` command. 
The folder contains no whitebox.exe

What am I doing wrong?

Regarding your answer:
If I understand you right, in your answer you are reading the raster from internal R raster file and processing it to an internal R raster file (via temporary file on disk). Is it both sides which are problematic to implement?

In some cases I would also be happy if it works on either side (e.g. process an R internal raster and store the result on disk or process a file stored on disk and receive the result as R internal raster.

**Comment by brownag** [comment]
wbt_init() should be passed the full path to the executable, not the parent folder. 

When you run `wbt_install()` with the default parameters for installation directory then the location will be `file.path(find.package('whitebox'), 'WBT', 'whitebox_tools.exe')`

---

`wbt()` allows you to pass references to R spatial objects (e.g. RasterLayer, SpatRaster). 

When the objects inherit from one of these classes, it uses methods such as `terra::sources()` to find the file location on disk. Rasters that exist only in memory are first written to a temporary file, and then that temp path is passed to `whitebox_tools` via command line. The output path is specified by the user in same command, and after the tool runs successfully, an object containing R spatial objects that references the user specified output path is returned. 

So, it appears as if the functions are dealing with standard R spatial objects, but it really is just a fancy wrapper that creates temporary files as needed based on the file references in those objects and returns R spatial objects based on user specified paths.
