### ISSUE TITLE
working with compressed tif-files

### ISSUE THREAD

**Issue by wiesehahn** [giswqs/whiteboxR#71]
I guess its more an issue related to WhiteboxTools, but since i am not sure I state it here. 

Trying to run commands for compressed TIF-files results in `System command had status 101`.

This is just true for certain compression types (e.g. LZMA, DEFLATE with predictor), while others (e.g. DEFLATE, LZW) work. Might be related to underlying GDAL version?

**Comment by brownag** [comment]
Yes, this is a known issue that, I believe, is not likely to be remedied in very near future. WhiteboxTools has a custom TIF file reader and GDAL is not used at all. See the manual for more info on supported data formats https://www.whiteboxgeo.com/manual/wbt_book/supported_formats.html

It is my understanding that the primary focus of development on WhiteboxTools right now is improving/adding to the tool sets rather than trying to extend e.g. the TIFF reader to work with all the possible cases that come with that format. The R package has no control over how data files are read, it just helps with the paths. See https://github.com/jblindsay/whitebox-tools/issues/97, https://github.com/jblindsay/whitebox-tools/issues/98, discussion in https://github.com/jblindsay/whitebox-tools/issues/137, and a workaround in https://github.com/jblindsay/whitebox-tools/issues/142

If you have a sample TIF that you can easily share, then perhaps you can make an issue on https://github.com/jblindsay/whitebox-tools/issues and they may be able to address it in a future update.
