### ISSUE TITLE
wbt_generalize_classified_raster(): System command had status 101 error

### ISSUE THREAD

**Issue by jacquomo** [giswqs/whiteboxR#81]
Hi, I am getting a 101 error when trying to use the wbt_generalize_classified_raster() tool in R4.0.2. I am running wrbt_majority_filter() and wbt_geomorphron() without issue. Any ideas what is going wrong?

E.g. code that throughs the 101 error:

r <-"./cod_grounds_geomorphron_100search_10deg_5tdist_masked.tif" #name of geomorphron output
wbt_generalize_classified_raster(
   r, 
   "./cod_grounds_geomorphron_100search_10deg_5tdist_gcr10L.tif",#name of final filtered geomorphron output
   min_size=10, #change as needed
   method="nearest",#"largest","nearest","longest"
   wd = NULL,
   verbose_mode = TRUE,
   compress_rasters = FALSE
 )

Returns:
Error running WhiteboxTools (generalize_classified_raster)
  whitebox.exe_path: "C:/Users/jmonk1/Dropbox/My PC (DOM-IMA-FDDM353)/Documents/R/win-library/4.0/whitebox/WBT/whitebox_tools.exe"; File exists? TRUE
  Arguments: --run=generalize_classified_raster  --input=./cod_grounds_geomorphron_100search_10deg_5tdist_masked.tif --output=./cod_grounds_geomorphron_100search_10deg_5tdist_gcr10L.tif --min_size=10 --method=nearest -v

System command had status 101
generalize_classified_raster - Elapsed Time: NA [did not run]

**Comment by jacquomo** [comment]
I am running the CRAN version. Just tried GitHub version as well. This is the error I get with either verison:

Error running WhiteboxTools (generalize_classified_raster)
  whitebox.exe_path: "C:/Users/jmonk1/Dropbox/My PC (DOM-IMA-FDDM353)/Documents/R/win-library/4.0/whitebox/WBT/whitebox_tools.exe"; File exists? TRUE
  Arguments: --run=generalize_classified_raster  --input="C:/temp1/test.tif" --output="C:/temp1/test_gcr10L.tif" --min_size=10 --method=nearest --compress_rasters=FALSE -v

System command had status 101
thread 'main' panicked at 'Unrecognized tool name generalize_classified_raster.', whitebox-tools-app\src\main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
generalize_classified_raster - Elapsed Time: NA [did not run]

I tried changing to absolute paths. Made no difference. The other functions (e.g. majority filter) still work fine with relative paths. Any further ideas?

**Comment by brownag** [comment]
Ah. Sorry about that, I should have checked this when I responded earlier. The key part of the error is this: 'Unrecognized tool name generalize_classified_raster'
> thread 'main' panicked at 'Unrecognized tool name generalize_classified_raster.', whitebox-tools-app\src\main.rs:72:21

Unfortunately the `generalized_classified_raster` tool is not part of the WhiteboxTools open core. It is part of an extension product. See more details on the manual page. https://www.whiteboxgeo.com/manual/wbt_book/available_tools/image_processing_tools_classification.html?highlight=generalize%20classified%20raster#generalizeclassifiedraster

I probably am going to need to add a more informative error for the cases where folks are using a WhiteboxTools installation no/only some extensions available. Thanks for reporting the issue, I'll leave it open until I can come up with a way to resolve it. There are a couple other pending issues surrounding tool metadata and incorporating related information into functions and documentation, and this is another item I should address along with that.

**Comment by jacquomo** [comment]
Ah, that makes sense. Thanks for looking into it for me.

**Comment by jacquomo** [comment]
I have purchased a license for the extension and have it running through the WB runner, but is giving the same error from within R. Any pointers?

**Comment by brownag** [comment]
I believe that you will need to have the extension unzipped to a subfolder of your WhiteboxTools installation directory called `/plugins/` in order for it to be recognized. You have a couple options

Either you can set your WhiteboxTools executable path to match the same one that the WB runner is using, the plugins should be installed there if you used `wbt.wbt_install_extensions()`. To set your EXE path for a session you can do `wbt_init(exe_path = "path/to/whitebox_tools.exe")`. For something longer lasting you can set `options(whitebox.exe_path = "...")` in your .Rprofile, or set a user environment variable R_WHITEBOX_EXE_PATH.

When you call `install_whitebox()` you can specify a installation path `pkg_dir` and you can then put the extensions into a subfolder `/plugins/` after installing. The default path puts it in your R library whitebox package installation folder i.e. `find.package("whitebox")` subfolder "WBT". Currently there aren't functions available in the R package to install and activate the extensions, so you will need to do that from the command line / from the python interface, as it seems you have done. 

I will look into implementing handling for installation/activation based on https://github.com/giswqs/whitebox-python, should be straightforward; incidentally I am a bit jealous... now I'll have to get myself the extensions!

**Comment by jacquomo** [comment]
Thanks. I have a play. You should get them, they are pretty amazing tools. Like all the WBT, they run sooooo fast which is great for iterating settings.

**Comment by brownag** [comment]
@jacquomo Great. I believe https://github.com/giswqs/whiteboxR/commit/d85b0639bd67cc8e1f8064d4ef966b96a51e88e2 was what we needed to get this working in R--so if you can please try with latest GH version

**Comment by jacquomo** [comment]
@brownag sorry for the delayed testing of this. Running fine now. Thanks for implementing the fixes.

**Comment by brownag** [comment]
No worries! Thanks for reporting the issue and testing the fixes

**Comment by MNewcomer** [comment]
Hello, I think I am encountering the same issue. Using R4.1.2. The hillshade function does not work when I use the function in R. The hillshade tool actually does works on my raster when I use the whitebox_runner.exe so this indicates to me the problem is not the raster. Here is the error it throws in R.

wbt_hillshade(dem = "D:/LBL/Wohler/Data/GIS Shapefiles/raster/brushDEMsm_5m_crs_burn.tif",output = "D:/LBL/Wohler/Data/GIS Shapefiles/raster/brush_hillshade.tif", azimuth = 315, altitude = 30)

[1] "hillshade - note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
Warning message:
In system(args2, intern = TRUE) :
  running command 'C:/Users/mnewcomer/Documents/R/win-library/4.1/whitebox/WBT/whitebox_tools.exe --run=hillshade  --dem=D:/LBL/Wohler/Data/GIS Shapefiles/raster/brushDEMsm_5m_crs_burn.tif --output=D:/LBL/Wohler/Data/GIS Shapefiles/raster/brush_hillshade.tif --azimuth=315 --altitude=30 -v' had status 101

**Comment by brownag** [comment]
> Hello, I think I am encountering the same issue. Using R4.1.2. The hillshade function does not work when I use the function in R. The hillshade tool actually does works on my raster when I use the whitebox_runner.exe so this indicates to me the problem is not the raster. Here is the error it throws in R.
> 
> wbt_hillshade(dem = "D:/LBL/Wohler/Data/GIS Shapefiles/raster/brushDEMsm_5m_crs_burn.tif",output = "D:/LBL/Wohler/Data/GIS Shapefiles/raster/brush_hillshade.tif", azimuth = 315, altitude = 30)
> 
> [1] "hillshade - note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace" Warning message: In system(args2, intern = TRUE) : running command 'C:/Users/mnewcomer/Documents/R/win-library/4.1/whitebox/WBT/whitebox_tools.exe --run=hillshade --dem=D:/LBL/Wohler/Data/GIS Shapefiles/raster/brushDEMsm_5m_crs_burn.tif --output=D:/LBL/Wohler/Data/GIS Shapefiles/raster/brush_hillshade.tif --azimuth=315 --altitude=30 -v' had status 101

Hello @MNewcomer: I believe yours is a different issue because the hillshade tool is not a plugin, like generalize_classified_raster, but rather part of the Whitebox "Open Core". 

If you can provide a sample DEM that has this error in a new issue we can take a look at it. When you run your example be sure to include the full output (so if there is anything more than that warning, like an error message from Rust, something like "thread main panicked...", please include in the new issue)

**Comment by brownag** [comment]
@MNewcomer I think the reason the system calls are failing is because of the spaces in your file paths. The quoting of commands was corrected a few versions ago. Please try again using a file path that does not contain spaces  in the folder names and see if you have better result, then update whitebox for proper quoting in commands.
